# Generated by Django 4.1.3 on 2023-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_app', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=20, unique=True)),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('product_title', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_count', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
