# Generated by Django 4.1.3 on 2023-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_id',
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
