# Generated by Django 4.1.3 on 2023-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra_app', '0004_order_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_count',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_title',
            field=models.TextField(),
        ),
    ]
